name: Build Telepush on Linux

on:
  release:
    types:
      - published

jobs:
  build-and-release:
    name: Build and add to Release

    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - platform: ubuntu-latest
            alias: linux
          - platform: macos-latest
            alias: mac
          - platform: windows-latest
            alias: win

    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get

      - name: Build
        run: go build -v -o telepush_${{ matrix.alias }}_amd64 .

      - name: Upload built executable to release (Win)
        uses: softprops/action-gh-release@v1
        if: runner.os == 'Windows'
        with:
          files: telepush_${{ matrix.alias }}_amd64
      - name: Upload built executable to release (Linux / Mac)
        uses: softprops/action-gh-release@v1
        if: runner.os != 'Windows'
        with:
          files: telepush_${{ matrix.alias }}_amd64.exe
